### ISSUE TITLE
Rename parsers.py to parser.py

### ISSUE THREAD

**Issue by lgvaz** [airctic/icedata#44]
The old datasets use the `parsers.py` convention but the template uses `parser.py` (which I believe is a better name)

So we need to rename the files to `parser.py` and update their respective `__init__.py` file.

**Comment by aadhav-n1** [comment]
Hi @lgvaz, I was looking to contribute to this project but couldn't find some suitable beginner issues. I still would need to understand the codebase for making future contributions, so I think this issue would be a good starting point for me :)

Could you assign me to this issue?

**Comment by aadhav-n1** [comment]
For refactoring the code, I think these are the files which need to be changed:

- icedata/datasets/voc/parsers.py
- icedata/datasets/coco/parsers.py
- icedata/datasets/pets/parsers.py
- icedata/datasets/birds/parsers.py
- icedata/datasets/fridge/parsers.py
- icedata/datasets/pennfudan/parsers.py

+ updating their respective `__init__.py` files.

**Comment by lgvaz** [comment]
Those are the necessary changes, correct =)

Thanks for the PR! I'll check it later on today
