### ISSUE TITLE
Fastcore 1.1 breaking changes

### ISSUE THREAD

**Issue by lgvaz** [airctic/icedata#63]
## 🐛 Bug
**Describe the bug**
Fastcore 1.1 contains a breaking change described [here](https://github.com/fastai/fastcore/blob/master/CHANGELOG.md):
- Remove Path.{read,write} (use Path.{read_text,write_text} instead) and change Path.{load,save} to functions load_pickle and save_pickle (#121)

We need to update our calls to `Path.read` to fix this issue.

**Comment by FraPochetti** [comment]
Hey @lgvaz can you assign this one to me too, please?

**Comment by lgvaz** [comment]
Done!

**Comment by FraPochetti** [comment]
PR submitted
