### ISSUE TITLE
AttributeError: module 'icedata' has no attribute 'voc'

### ISSUE THREAD

**Issue by ydcjeff** [airctic/icedata#84]
## 🐛 Bug

Install `icedata`
`pip install icedata` or `pip install git+https://github.com/airctic/icedata.git@master`

**Expected behavior**
`voc` should be imported properly

Env: colab

**Comment by lgvaz** [comment]
The install from pypi is definitely missing that, installation from master works though (I think your colab notebook was not refreshed)

I'll close the issue once it's updated on pypi
